
services:
  db:
    image: mysql:8.0
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=potato
      - MYSQL_ROOT_USER=carlinhoAndPotato
      - MYSQL_ROOT_DATABASE=sacoFromPotato
    
    ports:
      - 3309

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped